[tox]
envlist =
    py{310,311,312}-dj{42}
    py{310,311,312,313,314}-dj{50}
    py{310,311,312,313,314}-dj{51}
    py{310,311,312,313,314}-dj{52, latest}
skip_missing_interpreters = True

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps=
    django-ipware>=7.0.1,8.0.0
    dj42: Django>=4.2,<5.0
    dj50: Django>=5.0,<5.1
    dj51: Django>=5.1,<5.2
    dj52: Django>=5.2,<6.0
    djlatest: Django
commands=
    python load_tests.py
